import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  materialButtonViolet6: {
    height: 36,
    width: 115,
    position: "absolute",
    left: 0,
    top: 0,
    backgroundColor: "rgba(153,45,28,1)",
    borderRadius: 8,
    container: {
      backgroundColor: "#3F51B5",
      justifyContent: "center",
      alignItems: "center",
      flexDirection: "row",
      borderRadius: 2,
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.35,
      shadowRadius: 5,
      elevation: 2,
      minWidth: 88,
      paddingLeft: 16,
      paddingRight: 16,
    },
    red: {
      color: "rgba(255,255,255,1)",
      fontSize: 14,
      fontFamily: "merriweather-regular",
    },
  },
  icon: {
    top: 10,
    left: 8,
    position: "absolute",
    color: "rgba(255,255,255,1)",
    fontSize: 15,
  },
  materialButtonViolet6Stack: {
    width: 115,
    height: 36,
    marginTop: 339,
    marginLeft: 133,
  },
  image1: {
    top: 0,
    width: 375,
    height: 196,
    position: "absolute",
    opacity: 0.53,
    backgroundColor: "rgba(15,15, 15,1)",
    left: 0,
  },
  rect1: {
    top: 73,
    left: 2,
    width: 375,
    height: 87,
    position: "absolute",
    backgroundColor: "rgba(252,228,236,0.69)",
  },
  poorWomen1: {
    fontFamily: "merriweather-regular",
    color: "rgba(0,0,0,1)",
    fontSize: 20,
    marginTop: 31,
    marginLeft: 44,
  },
  image1Stack: {
    width: 377,
    height: 196,
    marginTop: -344,
  },
  materialIconTextButtonsFooter1: {
    height: 60,
    width: 375,
    marginTop: 503,
  },
  materialButtonViolet7: {
    height: 36,
    width: 115,
    position: "absolute",
    left: 0,
    top: 0,
    backgroundColor: "rgba(252,228,236,1)",
    borderRadius: 8,
  },
  icon3: {
    top: 10,
    left: 8,
    position: "absolute",
    color: "rgba(0,0,0,1)",
    fontSize: 15,
  },
  materialButtonViolet7Stack: {
    width: 115,
    height: 36,
    marginTop: -396,
    marginLeft: 133,
  },
  materialButtonViolet8: {
    height: 36,
    width: 115,
    position: "absolute",
    left: 0,
    top: 0,
    backgroundColor: "rgba(5,111,117,1)",
    borderRadius: 8,
  },
  icon4: {
    top: 10,
    left: 8,
    position: "absolute",
    color: "rgba(255,255,255,1)",
    fontSize: 15,
  },
  materialButtonViolet8Stack: {
    width: 115,
    height: 36,
    marginTop: 19,
    marginLeft: 133,
  },
  icon5: {
    color: "rgba(252,228,236,1)",
    fontSize: 45,
  },
  wines: {
    fontFamily: "merriweather-regular",
    color: "#121212",
    fontSize: 25,
    marginLeft: 2,
    marginTop: 9,
  },
  icon5Row: {
    height: 50,
    flexDirection: "row",
    marginTop: -243,
    marginLeft: 105,
    marginRight: 147,
  },
});
