import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  image1: {
    top: 0,
    width: 375,
    height: 196,
    position: "absolute",
    opacity: 0.53,
    backgroundColor: "rgba(15,15, 15,1)",
    left: 0,
  },
  rect1: {
    top: 73,
    left: 2,
    width: 375,
    height: 87,
    position: "absolute",
    backgroundColor: "rgba(252,228,236,0.69)",
  },
  poorWomen1: {
    fontFamily: "merriweather-regular",
    color: "rgba(0,0,0,1)",
    fontSize: 20,
    marginTop: 31,
    marginLeft: 44,
  },
  image1Stack: {
    width: 377,
    height: 196,
    marginTop: 31,
  },
  icon: {
    color: "rgba(201,178,186,1)",
    fontSize: 45,
    height: 43,
    width: 40,
  },
  text: {
    fontFamily: "merriweather-regular",
    color: "#121212",
    fontSize: 25,
    marginLeft: 9,
    marginTop: 10,
  },
  iconRow: {
    height: 43,
    flexDirection: "row",
    marginTop: 15,
    marginLeft: 60,
    marginRight: 127,
  },
  deleteAccountButton: {
    height: 43,
    width: 124,
    backgroundColor: "rgba(173,87,116,1)",
    borderRadius: 8,
    marginTop: 84,
    marginLeft: 126,
    container: {
      backgroundColor: "#3F51B5",
      justifyContent: "center",
      alignItems: "center",
      flexDirection: "row",
      borderRadius: 2,
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.35,
      shadowRadius: 5,
      elevation: 2,
      minWidth: 88,
      paddingLeft: 16,
      paddingRight: 16,
    },
    deleteAccount: {
      color: "rgba(255,255,255,1)",
      fontSize: 14,
      fontFamily: "merriweather-regular",
    },
  },
  materialIconTextButtonsFooter1: {
    height: 60,
    width: 375,
    marginTop: 318,
  },
  image2: {
    width: 159,
    height: 191,
    backgroundColor: "#fff",
    borderWidth: 4,
    borderColor: "rgba(252,228,236,1)",
    borderRadius: 8,
    opacity: 0.75,
    marginTop: -307,
    marginLeft: 107,
  },
});
