export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  materialIconTextButtonsFooter1: {
    height: 60,
    width: 375,
    marginTop: 734,
  },
  image1: {
    top: 0,
    width: 375,
    height: 196,
    position: "absolute",
    opacity: 0.53,
    backgroundColor: "rgba(15,15, 15,1)",
    left: 0,
  },
  rect1: {
    top: 73,
    left: 1,
    width: 375,
    height: 87,
    position: "absolute",
    backgroundColor: "rgba(252,228,236,0.69)",
  },
  poorWomen1: {
    fontFamily: "merriweather-regular",
    color: "rgba(0,0,0,1)",
    fontSize: 20,
    marginTop: 31,
    marginLeft: 45,
  },
  image1Stack: {
    width: 376,
    height: 196,
    marginTop: -763,
  },
  primaryButton: {
    height: 32,
    width: 179,
    backgroundColor: "#fff",
    marginTop: 82,
    marginLeft: 98,
  },
  materialButtonPink1: {
    height: 36,
    width: 179,
    borderRadius: 8,
    backgroundColor: "rgba(252,228,236,1)",
    marginTop: 23,
    marginLeft: 98,
    container: {
      backgroundColor: "#E91E63",
      justifyContent: "center",
      alignItems: "center",
      flexDirection: "row",
      borderRadius: 2,
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.35,
      shadowRadius: 5,
      elevation: 2,
      minWidth: 88,
      paddingLeft: 16,
      paddingRight: 16,
    },
    caption: {
      color: "#fff",
      fontSize: 14,
    },
  },
  group: {
    width: 179,
    height: 36,
    marginTop: 19,
    marginLeft: 98,
  },
  materialButtonPrimary: {
    height: 36,
    width: 179,
    borderRadius: 8,
    backgroundColor: "rgba(252,228,236,1)",
    container: {
      backgroundColor: "#2196F3",
      justifyContent: "center",
      alignItems: "center",
      flexDirection: "row",
      borderRadius: 2,
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.35,
      shadowRadius: 5,
      elevation: 2,
      minWidth: 88,
      paddingLeft: 16,
      paddingRight: 16,
    },
    editProfile: {
      color: "rgba(0,0,0,1)",
      fontSize: 14,
      fontFamily: "merriweather-regular",
    },
  },
  secondaryButton: {
    height: 36,
    width: 100,
    marginTop: 97,
    marginLeft: 139,
  },
  icon: {
    color: "rgba(252,228,236,1)",
    fontSize: 40,
  },
  profile: {
    fontFamily: "merriweather-regular",
    color: "#121212",
    fontSize: 25,
    marginLeft: 8,
    marginTop: 5,
  },
  iconRow: {
    height: 43,
    flexDirection: "row",
    marginTop: -342,
    marginLeft: 91,
    marginRight: 153,
  },
});
